
name: Commit Version Changes
description: Commits and pushes version changes to the repository

inputs:
  version:
    required: true
    description: "Version number to use in commit message"
  github-token:
    required: true
    description: "GitHub token for authentication"

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Update and Push Changes
      shell: bash
      run: |
        # Fetch and incorporate remote changes
        git fetch origin
        git pull --rebase origin ${{ github.ref }}
        
        # Check and commit changes if any
        if [[ -n "$(git status --porcelain)" ]]; then
          git add .
          git commit -m "Version ${{ inputs.version }}"
          git push
        else
          echo "No changes to commit"
        fi