name: terraform-forat-validate
description: Format and validate Terraform module for a given directory

inputs:
  directory:
    description: Directory to format and validate
    required: true
    default: '.'

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Format Terraform files
      id: format
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        terraform fmt -check -recursive
        if [ $? -ne 0 ]; then
          echo "Terraform files are not formatted correctly."
          exit 1
        fi

    - name: Validate Terraform files
      id: validate
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        terraform init
        terraform validate
        if [ $? -ne 0 ]; then
          echo "Terraform files are not valid."
          exit 1
        fi