name: terraform-docs
description: Create documentation for the given Terraform module

inputs:
  directory:
    description: Directory to format and validate
    required: true
    default: '.'

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Render terraform docs inside the README.md
      uses: terraform-docs/gh-actions@v1.3.0
      with:
        working-dir: ${{ inputs.directory }}
        output-file: README.md
        output-method: inject
        git-push: false
        recursive: false

    - name: Prepare artifact content
      id: prepare_artifact_content
      shell: bash
      run: |
        mkdir -p tfdocs/${{ inputs.directory }}
        cp "${{ inputs.directory }}/README.md" tfdocs/${{ inputs.directory }}/ || true

        uuid=$(uuidgen | tr '[:upper:]' '[:lower:]' | cut -d'-' -f1)
        echo "artifact_name=tfdocs-${uuid}" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.prepare_artifact_content.outputs.artifact_name }}
        path: tfdocs
        if-no-files-found: ignore
          