name: Deploy Dotnet App Service
description: Deploy a .NET application to Azure App Service

inputs:
  environment:
    required: true
    description: "Target environment for deployment"
  azure-environment:
    required: true
    description: "Azure environment to use"
  project:
    required: true
    description: "Project path to deploy"
  app-name:
    required: true
    description: "Name of the Azure Web App"
  config-file-path:
    required: false
    default: ''
    description: "Path to configuration file"
  dotnet-version:
    required: false
    default: '8.0.x'
    description: ".NET SDK version to use"
  github-token:
    required: true
    description: "GitHub token for authentication"
  azure-profile:
    required: true
    description: "Azure publish profile"
  codecov-token:
    required: false
    description: "Codecov token"

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}

    - name: Checkout AardexActions
      uses: actions/checkout@v4
      with:
        ref: main
        repository: aardex/AardexActions
        token: ${{ inputs.github-token }}
        path: AardexActions

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install python dependencies
      if: ${{ inputs.config-file-path != '' }}
      shell: bash
      run: pip install -r AardexActions/scripts/requirements.txt

    - name: Setup config
      if: ${{ inputs.config-file-path != '' }}
      shell: bash
      run: |
        python3 AardexActions/scripts/azure/update-config.py --token ${{ inputs.github-token }} --repo ${{ github.repository }} --repo-env ${{ inputs.environment }} --config-path ${{ inputs.config-file-path }}

    - name: Build and package application
      uses: aardex/AardexActions/dotnet-build@main
      with:
        build-target: 'Release'
        working-directory: ${{ inputs.project }}
        dotnet-version: ${{ inputs.dotnet-version }}
        output-path: 'app'
        github-token: ${{ inputs.github-token }}
        codecov-token: ${{ inputs.codecov-token }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'app-${{ inputs.app-name }}-${{ inputs.azure-environment }}'
        publish-profile: ${{ inputs.azure-profile }}
        package: '${{ inputs.project }}/app'