name: terraform-version-update
description: Increment update and return a Terraform module version

permissions:
  contents: write

inputs:
  type:
    description: "The type of version increment (major, minor, patch, release, release-candidate, alpha)"
    required: true
    type: choice
    options:
      - major
      - minor
      - patch
      - release
      - release-candidate
      - alpha

  version:
    description: "The current version of the Terraform module (optional if version file exists)"
    type: string
    default: ''

  version_file:
    description: "The file containing the current version (default: version.txt)"
    type: string
    default: "version.txt"

outputs:
  version:
    description: "The new version number"
    value: ${{ steps.version_compute.outputs.version }}

runs:
  using: composite
  steps:
    - name: Deprecated Action Warning
      shell: bash
      run: |
        echo "WARNING: This action is deprecated and will be removed in future releases. Please migrate to the 'github-version-update' action."
        exit 1