name: module-directories
description: List all module directories in a project

inputs:
  exclude_patterns:
    description: |
      List of additional directory patterns to exclude from the search (separated by newlines or commas)
    required: false
    default: ""

outputs:
  directories:
    description: Array of module directories
    value: ${{ steps.module-directories.outputs.directories }}

runs:
  using: composite
  steps:
    - name: Get Terraform module directories
      id: module-directories
      shell: bash
      run: |
        EXCLUDE_FILTER=$(echo "${{ inputs.exclude_patterns }}" | tr ',' '\n' | sed 's/.*/-not -path &/' | tr '\n' ' ')
        echo "Excluding: ${EXCLUDE_FILTER}\n"

        MODULE_DIRS=$(find . -type f -name "*.tf" \
          -not -path "*/.terraform/*" \
          -not -path "*/.git/*" \
          -not -path "*/vendor/*" \
          ${EXCLUDE_FILTER} \
          -exec grep -l "required_version" {} \; | xargs -n1 dirname | sort -u | jq -R . | jq -sc .)
        
        echo -e "Directories:\n${MODULE_DIRS}"
        echo "directories=$MODULE_DIRS" >> $GITHUB_OUTPUT