name: module-directories
description: List all module directories in a project

outputs:
  directories:
    description: Array of module directories
    value: ${{ steps.module-directories.outputs.directories }}

runs:
  using: composite
  steps:
    - name: Get Terraform module directories
      id: module-directories
      shell: bash
      run: |
        MODULE_DIRS=$(find . -type f -name "*.tf" \
            -not -path "*/.terraform/*" \
            -not -path "*/.git/*" \
            -not -path "*/vendor/*" \
            -exec grep -l "required_version" {} \; \
          | xargs -n1 dirname \
          | sort -u | jq -R . | jq -sc .)
        echo -e "Directories:\n${MODULE_DIRS}"
        echo "directories=$MODULE_DIRS" >> $GITHUB_OUTPUT