name: module-directories
description: List all module directories in a project

inputs:
  exclude_patterns:
    description: |
      List of additional directory patterns to exclude from the search (separated by newlines or commas)
    required: false
    default: ""

outputs:
  directories:
    description: Array of module directories
    value: ${{ steps.module-directories.outputs.directories }}

runs:
  using: composite
  steps:
    - name: Get Terraform module directories
      id: module-directories
      shell: bash
      run: |
        bash ${{ github.action_path }}/action.sh "${{ inputs.exclude_patterns }}"