name: Azure Deploy Dotnet Docker
description: Build & Deploy a Docker application to Azure Container Apps

inputs:
  environment:
    required: true
    description: "Target environment for deployment"
  image-name:
    required: true
    description: "Name of the Docker image"
  version:
    required: false
    description: "Version tag for the Docker image. If not provided, will use version from Directory.Build.props"
  config-file-path:
    required: false
    default: ''
    description: "Path to configuration file. Only required for .Net projects."
  github-token:
    required: true
    description: "GitHub token for authentication"
  acr-login-server:
    required: true
    description: "Azure Container Server Name"
  acr-username:
    required: true
    description: "Azure Container Registry Username"
  acr-password:
    required: true
    description: "Azure Container Registry Password"
  docker-directory:
    required: false
    default: 'docker'
    description: "Path to the Dockerfile"
  platforms:
    required: false
    default: 'linux/amd64'
    description: "Comma-separated list of target platforms for multi-arch build"
  skip-check:
    required: false
    default: 'false'
    description: "Skip vulnerability check"

runs:
  using: composite
  steps:
    - name: Checkout AardexActions
      uses: actions/checkout@v5
      with:
        ref: main
        repository: aardex/AardexActions
        token: ${{ inputs.github-token }}
        path: AardexActions

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install python dependencies
      shell: bash
      run: pip install -r AardexActions/scripts/requirements.txt

    - name: Extract version from Directory.Build.props if needed
      if: ${{ inputs.version == '' }}
      id: extract-version
      shell: bash
      run: |
        python3 AardexActions/scripts/azure/get_version.py --set-output

    - name: Setup config
      if: ${{ inputs.config-file-path != '' }}
      shell: bash
      run: |
        python3 AardexActions/scripts/azure/update-config.py --token ${{ inputs.github-token }} --repo ${{ github.repository }} --repo-env ${{ inputs.environment }} --config-path ${{ inputs.config-file-path }}

    - name: Build and push Docker image
      uses: aardex/AardexActions/azure-publish-docker@features/INFRA-214
      with:
        image-name: ${{ inputs.image-name }}
        version: ${{ inputs.version != '' && inputs.version || env.VERSION }}
        github-token: ${{ inputs.github-token }}
        acr-login-server: ${{ inputs.acr-login-server }}
        acr-username: ${{ inputs.acr-username }}
        acr-password: ${{ inputs.acr-password }}
        docker-directory: ${{ inputs.docker-directory }}
        platforms: ${{ inputs.platforms }}
        skip-check: ${{ inputs.skip-check }}