name: Azure Deploy Dotnet Docker
description: Build & Deploy a Docker application to Azure Container Apps

inputs:
  environment:
    required: true
    description: "Target environment for deployment"
  image-name:
    required: true
    description: "Name of the Docker image"
  version:
    required: false
    description: "Version tag for the Docker image. If not provided, will use version from Directory.Build.props"
  config-file-path:
    required: false
    default: ''
    description: "Path to configuration file. Only required for .Net projects."
  github-token:
    required: true
    description: "GitHub token for authentication"
  subscription-id:
    required: true
    description: "Azure Subscription ID"
  acr-login-server:
    required: true
    description: "Azure Container Server Name"
  acr-username:
    required: false
    description: "Azure Container Registry Username (optional if using azure-credentials)"
  acr-password:
    required: false
    description: "Azure Container Registry Password (optional if using azure-credentials)"
  azure-credentials:
    required: false
    description: "Azure credentials for authentication"
  docker-directory:
    required: false
    default: 'docker'
    description: "Path to the Dockerfile"
  platforms:
    required: false
    default: 'linux/amd64'
    description: "Comma-separated list of target platforms for multi-arch build"

outputs:
  version:
    description: "The version used to build and push the Docker image"
    value: ${{ steps.resolve_version.outputs.version }}

runs:
  using: composite
  steps:

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install python dependencies
      shell: bash
      run: pip install -r "${{ github.action_path }}/../scripts/requirements.txt"

    - name: Extract version from Directory.Build.props if needed
      if: ${{ inputs.version == '' }}
      shell: bash
      run: |
        python3 "${{ github.action_path }}/../scripts/nuget/get_version.py" --set-output

    - name: Resolve version
      id: resolve_version
      shell: bash
      run: |
        resolved="${{ inputs.version != '' && inputs.version || env.VERSION }}"
        echo "Resolved version: ${resolved}"
        echo "version=${resolved}" >> "$GITHUB_OUTPUT"

    - name: Setup config
      if: ${{ inputs.config-file-path != '' }}
      shell: bash
      run: |
        python3 "${{ github.action_path }}/../scripts/azure/update-config.py" --token ${{ inputs.github-token }} --repo ${{ github.repository }} --repo-env ${{ inputs.environment }} --config-path ${{ inputs.config-file-path }}

    - name: Build and push Docker image
      uses: aardex/AardexActions/azure-publish-docker@main
      with:
        image-name: ${{ inputs.image-name }}
        version: ${{ steps.resolve_version.outputs.version }}
        github-token: ${{ inputs.github-token }}
        subscription-id: ${{ inputs.subscription-id }}
        acr-login-server: ${{ inputs.acr-login-server }}
        acr-username: ${{ inputs.acr-username }}
        acr-password: ${{ inputs.acr-password }}
        azure-credentials: ${{ inputs.azure-credentials }}
        docker-directory: ${{ inputs.docker-directory }}
        platforms: ${{ inputs.platforms }}