name: Deploy Dotnet Function
description: Deploy a .NET function to Azure

inputs:
  environment:
    required: true
    description: "Target environment for deployment"
  github-token:
    required: true
    description: "GitHub token for authentication"
    
runs:
  using: composite
  steps:
    - uses: chrnorm/deployment-action@v2
      name: Create GitHub deployment
      id: deployment
      with:
        token: '${{ inputs.github-token }}'
        environment: ${{ inputs.environment }}
        
    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@v2
      with:
        token: '${{ github-token }}'
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}
        state: 'success'
    
    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@v2
      with:
        token: '${{ github-token }}'
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}
        state: 'failure'