name: github-commit-push
description: Commit and push changes to the GitHub repository

inputs:
  message:
    description: "Commit message to use for the changes"    
    default: "Update source"

  github-token:
    description: "GitHub token for authentication"    
    default: ''

runs:
  using: composite
  steps:
    - name: Commit and Push Documentation Changes
      shell: bash
      run: |
        # if [ -n "${{ inputs.github-token }}" ]; then
        #   echo "Use \"Github Action User\"."
        #   git config --global user.email "actions@github.com"
        #   git config --global user.name "GitHub Actions"
        #   git config --global user.password "${{ inputs.github-token }}"
        # fi 
        
        git diff --quiet && git diff --cached --quiet && { echo "No changes to commit."; exit 0; }
        git add . && git commit -m "${{ inputs.message }}" && git push || echo "Nothing to push!"