name: Release Dotnet Component
description: Increment and publish a release version of a nuget

inputs:
  github-token:
    required: true
    description: "GitHub token for authentication"
  version:
    required: false
    description: "The version number (manual)"
    default: ""

runs:
  using: composite
  steps:

    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        token: ${{ inputs.github-token }}


    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Determine version
      id: determine_version
      shell: bash
      run: |
        version="${{ inputs.version }}"
        [[ -n "${{ inputs.version }}" ]] || version=$(python3 "${{ github.action_path }}/../scripts/nuget/generate-version.py" release)
        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Update package version
      shell: bash
      run: python3 "${{ github.action_path }}/../scripts/nuget/update-version.py" --new-version ${{ steps.determine_version.outputs.version }}


    - name: Commit Changes
      uses: aardex/AardexActions/github-commit-push@main
      with:
        message: Release ${{ steps.determine_version.outputs.version }}
        github-token: ${{ inputs.github-token }}

    - name: Create Release
      uses: aardex/AardexActions/github-create-tag-release@main
      with:
        version: ${{ steps.determine_version.outputs.version }}
        github-token: ${{ inputs.github-token }}