name: terraform-deploy
description: Deploy Terraform to Azure

inputs:
  azure-credentials:
    required: true
    description: "Azure credentials for authentication"
  azure-subscription:
    required: false
    description: "Azure subscription to deploy to (defaults to first subscription in credentials)"
  directory:
    required: false
    default: 'terraform'
    description: Terraform directory to deploy
  apply:
    required: false
    default: 'false'
    description: "Whether to run terraform apply"
  needs-approval:
    required: false
    default: 'true'
    description: "Whether to require approval for terraform apply"
  tfvars-content:
    required: false
    description: "Content of the terraform.tfvars file (as a single string, from secrets or workflow input)"
  github-token:
    required: true
    description: "GitHub token for private module access"

runs:
  using: composite
  steps:
    - name: Login to Azure
      shell: bash
      run: |
        CLIENT_ID=$(echo '${{ inputs.azure-credentials }}' | jq -r .clientId)
        CLIENT_SECRET=$(echo '${{ inputs.azure-credentials }}' | jq -r .clientSecret)
        if [ -n "${{ inputs.azure-subscription }}" ]; then
          SUBSCRIPTION_ID=${{ inputs.azure-subscription }}
        else
          SUBSCRIPTION_ID=$(echo '${{ inputs.azure-credentials }}' | jq -r .subscriptionId)
        fi
        TENANT_ID=$(echo '${{ inputs.azure-credentials }}' | jq -r .tenantId)
        az login --service-principal -u "$CLIENT_ID" -p "$CLIENT_SECRET" --tenant "$TENANT_ID"
        az account set --subscription "$SUBSCRIPTION_ID"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.3

    - name: Configure Git credential URL
      shell: bash
      run: |
        git config --global url."https://${{ inputs.github-token }}@github.com/".insteadOf "https://github.com/"

    - name: Create terraform.tfvars from input
      if: ${{ inputs.tfvars-content && inputs.tfvars-content != '' }}
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        echo "📝 Creating terraform.tfvars from input"
        cat <<EOF > terraform.tfvars
        ${{ inputs.tfvars-content }}
        EOF
        echo "::add-mask::${{ inputs.tfvars-content }}"
        echo "✅ terraform.tfvars created successfully"

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: terraform init -upgrade -input=false

    - name: Terraform Validate
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: terraform validate -no-color

    - name: Terraform Plan
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        if [ -f "terraform.tfvars" ]; then
          echo "✅ terraform.tfvars found, using it."
          terraform plan \
            -input=false \
            -no-color \
            -var-file="terraform.tfvars" \
            -out=tfplan.tfplan > result.txt 2>&1
        else
          echo "⚠️ No terraform.tfvars found, running plan without it."
          terraform plan \
            -input=false \
            -no-color \
            -out=tfplan.tfplan > result.txt 2>&1
        fi

    - name: Terraform Show
      if: always()
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: terraform show -json tfplan.tfplan > tfplan.json

    - name: Upload Plan Artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: |
          ${{ inputs.directory }}/tfplan.tfplan
          ${{ inputs.directory }}/tfplan.json
          ${{ inputs.directory }}/result.txt
        retention-days: 15

    - name: Terraform Apply (opt-in)
      if: ${{ inputs.apply == 'true' }}
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: terraform apply -input=false -auto-approve tfplan.tfplan
