name: terraform-docs-index
description: Create table of content for Terraform Documentation

inputs:
  directory:
    description: Directory to process
    required: true
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Run script
      shell: bash
      working-dir: ${{ inputs.directory }}
      run: |
        bash ${{ github.action_path }}/action.sh