name: Deploy .Net Docker to Container App
description: Deploy a Docker .NET application to Azure Container Apps

inputs:
  environment:
    required: true
    description: "Target environment for deployment"
  azure-environment:
    required: true
    description: "Azure environment to use"
  project:
    required: true
    description: "Project path to deploy"
  app-name:
    required: true
    description: "Name of the Azure Container App"
  version:
    required: false
    description: "Version tag for the Docker image"
    default: 'latest'
  config-file-path:
    required: false
    default: ''
    description: "Path to configuration file"
  github-token:
    required: true
    description: "GitHub token for authentication"
  azure-credentials:
    required: true
    description: "Azure credentials for authentication"
  acr-name:
    required: true
    description: "Azure Container Registry name"
  resource-group:
    required: true
    description: "Azure Resource Group name"

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}

    - name: Checkout AardexActions
      uses: actions/checkout@v4
      with:
        ref: main
        repository: aardex/AardexActions
        token: ${{ inputs.github-token }}
        path: AardexActions

    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install python dependencies
      if: ${{ inputs.config-file-path != '' }}
      shell: bash
      run: pip install -r AardexActions/scripts/requirements.txt

    - name: Setup config
      if: ${{ inputs.config-file-path != '' }}
      shell: bash
      run: |
        python3 AardexActions/scripts/azure/update-config.py --token ${{ inputs.github-token }} --repo ${{ github.repository }} --repo-env ${{ inputs.environment }} --config-path ${{ inputs.config-file-path }}

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ inputs.acr-name }}.azurecr.io
        username: ${{ inputs.acr-name }}
        password: ${{ inputs.azure-credentials }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ inputs.acr-name }}.azurecr.io/${{ inputs.app-name }}:${{ inputs.version }}
          ${{ inputs.acr-name }}.azurecr.io/${{ inputs.app-name }}:latest
        cache-from: type=registry,ref=${{ inputs.acr-name }}.azurecr.io/${{ inputs.app-name }}:buildcache
        cache-to: type=registry,ref=${{ inputs.acr-name }}.azurecr.io/${{ inputs.app-name }}:buildcache,mode=max
        
    - name: Scan Docker image for vulnerabilities
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: ${{ inputs.acr-name }}.azurecr.io/${{ inputs.app-name }}:${{ inputs.version }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

    - name: Deploy to Azure Container Apps
      shell: bash
      run: |
        az config set extension.use_dynamic_install=yes_without_prompt
        az containerapp update \
          --name ${{ inputs.app-name }}-${{ inputs.azure-environment }} \
          --resource-group ${{ inputs.resource-group }} \
          --image ${{ inputs.acr-name }}.azurecr.io/${{ inputs.app-name }}:${{ inputs.version }} \
          --registry-server ${{ inputs.acr-name }}.azurecr.io
